{{- range .Values.configMaps }} 
  {{- if .create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data: 
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
---   
{{- end }}
